# Auto-generated Terraform module invocation for storage container: new_container
# Generated by workflow run 3 at 2025-10-22T09:27:27Z

module "storage_container_3" {
  source = "./modules/blobstorage"

  resource_group_name  = azurerm_resource_group.default.name
  storage_account_name = local.storage_account_name
  location             = azurerm_resource_group.default.location
  container_name       = "new_container"

  tags = local.tags
}
