# Auto-generated Terraform module invocation for storage container: clwatst123now
# Generated by workflow run 7 at 2025-10-22T12:37:18Z

module "storage_container_7" {
  source = "./modules/blobstorage"

  resource_group_name  = azurerm_resource_group.default.name
  storage_account_name = local.storage_account_name
  location             = azurerm_resource_group.default.location
  container_name       = "clwatst123now"

  tags = local.tags
}
