# Auto-generated Terraform module invocation for storage container: clwatst123now3
# Generated by workflow run 9 at 2025-10-22T12:56:44Z

module "storage_container_9" {
  source = "./modules/blobstorage"

  resource_group_name  = azurerm_resource_group.default.name
  location             = azurerm_resource_group.default.location
  container_name       = "clwatst123now3"

  tags = local.tags
}
