# Auto-generated Terraform module invocation for storage container: default
# Generated by workflow run 8 at 2025-10-22T12:51:48Z

module "storage_container_8" {
  source = "./modules/blobstorage"

  resource_group_name  = azurerm_resource_group.default.name
  location             = azurerm_resource_group.default.location
  container_name       = "default"

  tags = local.tags
}
