# Auto-generated Terraform module invocation for storage container: clwaltest1234now
# Generated by workflow run 6 at 2025-10-22T09:49:16Z

module "storage_container_6" {
  source = "./modules/blobstorage"

  resource_group_name  = azurerm_resource_group.default.name
  storage_account_name = local.storage_account_name
  location             = azurerm_resource_group.default.location
  container_name       = "clwaltest1234now"

  tags = local.tags
}
