# Auto-generated Terraform module invocation for storage container: clwatest123now
# Generated by workflow run 5 at 2025-10-22T09:39:13Z

module "storage_container_5" {
  source = "./modules/blobstorage"

  resource_group_name  = azurerm_resource_group.default.name
  storage_account_name = local.storage_account_name
  location             = azurerm_resource_group.default.location
  container_name       = "clwatest123now"

  tags = local.tags
}
