name: Create Storage Container Module File

on:
  workflow_dispatch:
    inputs:
      container_name:
        description: "Name of the storage container to create"
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-module-file:
    runs-on: ubuntu-latest
    environment: dev-workflow-automation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set variables
        id: vars
        run: |
          RUN_NUMBER=${GITHUB_RUN_NUMBER}
          INPUT_NAME='${{ inputs.container_name }}'
          # sanitize input (lowercase, remove spaces)
          SANITIZED_NAME=$(echo "$INPUT_NAME" | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9-')
          BRANCH="feature/storage-container-${SANITIZED_NAME}-${RUN_NUMBER}"
          FILE="container-${RUN_NUMBER}.tf"
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          echo "file=$FILE" >> $GITHUB_OUTPUT
          echo "sanitized=$SANITIZED_NAME" >> $GITHUB_OUTPUT

      - name: Create module file
        run: |
          FILE='${{ steps.vars.outputs.file }}'
          CONTAINER='${{ inputs.container_name }}'
          printf '%s\n' \
            "# Auto-generated Terraform module invocation for storage container: $CONTAINER" \
            "# Generated by workflow run $GITHUB_RUN_NUMBER at $(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
            "" \
            "module \"storage_container_${GITHUB_RUN_NUMBER}\" {" \
            "  source = \"./modules/blobstorage\"" \
            "" \
            "  resource_group_name  = azurerm_resource_group.default.name" \
            "  storage_account_name = local.storage_account_name" \
            "  location             = azurerm_resource_group.default.location" \
            "  container_name       = \"$CONTAINER\"" \
            "" \
            "  tags = local.tags" \
            "}" \
            > "$FILE"
          git add "$FILE"

      - name: Create branch and commit
        run: |
          BRANCH='${{ steps.vars.outputs.branch }}'
          git checkout -b "$BRANCH"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -m "Add storage container module file for '${{ inputs.container_name }}' (run $GITHUB_RUN_NUMBER)"

      - name: Push branch
        run: |
          BRANCH='${{ steps.vars.outputs.branch }}'
          git push origin "$BRANCH"

      - name: Create pull request
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          BRANCH='${{ steps.vars.outputs.branch }}'
          gh pr create \
            --title "Add storage container '${{ inputs.container_name }}' (run $GITHUB_RUN_NUMBER)" \
            --body "This PR adds a Terraform module invocation file (${{ steps.vars.outputs.file }}) for storage container '${{ inputs.container_name }}', generated by workflow run $GITHUB_RUN_NUMBER." \
            --base main \
            --head "$BRANCH" || echo "PR already exists or creation failed"
