name: "Terraform"

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    environment: dev
    env:
      ARM_CLIENT_ID: "${{ vars.AZURE_CLIENT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ vars.AZURE_SUBSCRIPTION_ID }}"
      ARM_TENANT_ID: "${{ vars.AZURE_TENANT_ID }}"
      ARM_USE_OIDC: true
      ARM_USE_AZUREAD: true

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -input=false -no-color > plan.txt
          cat plan.txt

      - name: Comment PR with Terraform Plan
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PLAN_SUMMARY=$(head -300 plan.txt)
          gh pr comment ${{ github.event.pull_request.number }} --body $'#### Terraform Plan\n\n```\n'$PLAN_SUMMARY'\n```\n*Full plan output truncated to first 300 lines.*'
        shell: bash

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
